<?php

        # this file was cloned from https://github.com/whosonfirst/flamework-whosonfirst/

        ########################################################################

        # this file was also generated by robots on 2018-04-26T11:35:14.833604
        # https://github.com/whosonfirst/flamework-whosonfirst/blob/master/utils/mk-spec.py
        # https://github.com/whosonfirst/flamework-whosonfirst/blob/master/Makefile

        ########################################################################

        $GLOBALS['whosonfirst_brands_sizes']['__SPEC__'] = '{"1141959937": {"min": 6, "max": 10, "label": "extra-extra small", "id": 1141959937, "size": "XXS"}, "1141959931": {"min": 11, "max": 20, "label": "extra small", "id": 1141959931, "size": "XS"}, "1158864409": {"min": 3, "max": 5, "label": "extra-extra-extra small", "id": 1158864409, "size": "XXXS"}, "1158862561": {"min": 1, "max": 2, "label": "onesie", "id": 1158862561, "size": "O"}, "1141959923": {"min": 21, "max": 50, "label": "small", "id": 1141959923, "size": "S"}, "1141959925": {"min": 101, "max": 500, "label": "large", "id": 1141959925, "size": "L"}, "1141959927": {"min": 51, "max": 100, "label": "medium", "id": 1141959927, "size": "M"}, "1141959929": {"min": 501, "max": 5000, "label": "extra large", "id": 1141959929, "size": "XL"}, "1158864411": {"min": 10001, "label": "extra-extra-extra large", "id": 1158864411, "size": "XXXL"}, "1141959935": {"min": 5001, "max": 10000, "label": "extra-extra large", "id": 1141959935, "size": "XXL"}}';

        ########################################################################
        # the end
