<?php

	# this file was also generated by robots on 2017-09-27 16:03:33
	# https://github.com/whosonfirst/whosonfirst-www-api/blob/master/bin/mk_countries.php
	# https://github.com/whosonfirst/whosonfirst-www-api/blob/master/Makefile

	########################################################################

	$GLOBALS['whosonfirst_countries'] = array(
		'AQ' => array(
			'wof:id' => 85632715,
			'wof:name' => 'Antarctica'
		),
		'RU' => array(
			'wof:id' => 85632685,
			'wof:name' => 'Russia'
		),
		'CA' => array(
			'wof:id' => 85633041,
			'wof:name' => 'Canada'
		),
		'US' => array(
			'wof:id' => 85633793,
			'wof:name' => 'United States'
		),
		'CN' => array(
			'wof:id' => 85632695,
			'wof:name' => 'China'
		),
		'BR' => array(
			'wof:id' => 85633009,
			'wof:name' => 'Brazil'
		),
		'AU' => array(
			'wof:id' => 85632793,
			'wof:name' => 'Australia'
		),
		'GL' => array(
			'wof:id' => 85633217,
			'wof:name' => 'Greenland'
		),
		'KZ' => array(
			'wof:id' => 85632307,
			'wof:name' => 'Kazakhstan'
		),
		'AR' => array(
			'wof:id' => 85632505,
			'wof:name' => 'Argentina'
		),
		'IN' => array(
			'wof:id' => 85632469,
			'wof:name' => 'India'
		),
		'DZ' => array(
			'wof:id' => 85632451,
			'wof:name' => 'Algeria'
		),
		'CD' => array(
			'wof:id' => 85632643,
			'wof:name' => 'Democratic Republic of the Congo'
		),
		'MN' => array(
			'wof:id' => 85632439,
			'wof:name' => 'Mongolia'
		),
		'MX' => array(
			'wof:id' => 85633293,
			'wof:name' => 'Mexico'
		),
		'SA' => array(
			'wof:id' => 85632253,
			'wof:name' => 'Saudi Arabia'
		),
		'SD' => array(
			'wof:id' => 85632751,
			'wof:name' => 'Sudan'
		),
		'IR' => array(
			'wof:id' => 85632361,
			'wof:name' => 'Iran'
		),
		'ID' => array(
			'wof:id' => 85632203,
			'wof:name' => 'Indonesia'
		),
		'LY' => array(
			'wof:id' => 85632627,
			'wof:name' => 'Libya'
		),
		'ZA' => array(
			'wof:id' => 85633813,
			'wof:name' => 'South Africa'
		),
		'TD' => array(
			'wof:id' => 85632325,
			'wof:name' => 'Chad'
		),
		'ML' => array(
			'wof:id' => 85632553,
			'wof:name' => 'Mali'
		),
		'PE' => array(
			'wof:id' => 85632521,
			'wof:name' => 'Peru'
		),
		'AO' => array(
			'wof:id' => 85632281,
			'wof:name' => 'Angola'
		),
		'NE' => array(
			'wof:id' => 85632269,
			'wof:name' => 'Niger'
		),
		'ET' => array(
			'wof:id' => 85632257,
			'wof:name' => 'Ethiopia'
		),
		'CO' => array(
			'wof:id' => 85632519,
			'wof:name' => 'Colombia'
		),
		'BO' => array(
			'wof:id' => 85632623,
			'wof:name' => 'Bolivia'
		),
		'MR' => array(
			'wof:id' => 85632679,
			'wof:name' => 'Mauritania'
		),
		'EG' => array(
			'wof:id' => 85632581,
			'wof:name' => 'Egypt'
		),
		'NO' => array(
			'wof:id' => 85633341,
			'wof:name' => 'Norway'
		),
		'PK' => array(
			'wof:id' => 85632659,
			'wof:name' => 'Pakistan'
		),
		'TR' => array(
			'wof:id' => 85632393,
			'wof:name' => 'Turkey'
		),
		'CL' => array(
			'wof:id' => 85633057,
			'wof:name' => 'Chile'
		),
		'SE' => array(
			'wof:id' => 85633789,
			'wof:name' => 'Sweden'
		),
		'TZ' => array(
			'wof:id' => 85632227,
			'wof:name' => 'Tanzania'
		),
		'NG' => array(
			'wof:id' => 85632735,
			'wof:name' => 'Nigeria'
		),
		'VE' => array(
			'wof:id' => 85632317,
			'wof:name' => 'Venezuela'
		),
		'UA' => array(
			'wof:id' => 85633805,
			'wof:name' => 'Ukraine'
		),
		'NA' => array(
			'wof:id' => 85632535,
			'wof:name' => 'Namibia'
		),
		'FR' => array(
			'wof:id' => 85633147,
			'wof:name' => 'France'
		),
		'MZ' => array(
			'wof:id' => 85632729,
			'wof:name' => 'Mozambique'
		),
		'ZM' => array(
			'wof:id' => 85632559,
			'wof:name' => 'Zambia'
		),
		'AF' => array(
			'wof:id' => 85632229,
			'wof:name' => 'Afghanistan'
		),
		'FI' => array(
			'wof:id' => 85633143,
			'wof:name' => 'Finland'
		),
		'MM' => array(
			'wof:id' => 85632181,
			'wof:name' => 'Myanmar'
		),
		'MA' => array(
			'wof:id' => 85632693,
			'wof:name' => 'Morocco'
		),
		'ES' => array(
			'wof:id' => 85633129,
			'wof:name' => 'Spain'
		),
		'SS' => array(
			'wof:id' => 85632657,
			'wof:name' => 'South Sudan'
		),
		'MG' => array(
			'wof:id' => 85632223,
			'wof:name' => 'Madagascar'
		),
		'CF' => array(
			'wof:id' => 85632391,
			'wof:name' => 'Central African Republic'
		),
		'BW' => array(
			'wof:id' => 85632235,
			'wof:name' => 'Botswana'
		),
		'TM' => array(
			'wof:id' => 85632671,
			'wof:name' => 'Turkmenistan'
		),
		'UZ' => array(
			'wof:id' => 85632645,
			'wof:name' => 'Uzbekistan'
		),
		'KE' => array(
			'wof:id' => 85632329,
			'wof:name' => 'Kenya'
		),
		'DE' => array(
			'wof:id' => 85633111,
			'wof:name' => 'Germany'
		),
		'TH' => array(
			'wof:id' => 85632293,
			'wof:name' => 'Thailand'
		),
		'PL' => array(
			'wof:id' => 85633723,
			'wof:name' => 'Poland'
		),
		'SO' => array(
			'wof:id' => 85632379,
			'wof:name' => 'Somalia'
		),
		'IQ' => array(
			'wof:id' => 85632191,
			'wof:name' => 'Iraq'
		),
		'YE' => array(
			'wof:id' => 85632499,
			'wof:name' => 'Yemen'
		),
		'JP' => array(
			'wof:id' => 85632429,
			'wof:name' => 'Japan'
		),
		'PG' => array(
			'wof:id' => 85632347,
			'wof:name' => 'Papua New Guinea'
		),
		'CM' => array(
			'wof:id' => 85632245,
			'wof:name' => 'Cameroon'
		),
		'PY' => array(
			'wof:id' => 85632355,
			'wof:name' => 'Paraguay'
		),
		'GB' => array(
			'wof:id' => 85633159,
			'wof:name' => 'United Kingdom'
		),
		'ZW' => array(
			'wof:id' => 85632243,
			'wof:name' => 'Zimbabwe'
		),
		'IT' => array(
			'wof:id' => 85633253,
			'wof:name' => 'Italy'
		),
		'NZ' => array(
			'wof:id' => 85633345,
			'wof:name' => 'New Zealand'
		),
		'XX' => array(
			'wof:id' => 1126113567,
			'wof:name' => 'Socialist Federal Republic of Yugoslavia'
		),
		'XX' => array(
			'wof:id' => 1108955789,
			'wof:name' => 'Kingdom of Yugoslavia'
		),
		'BY' => array(
			'wof:id' => 85632395,
			'wof:name' => 'Belarus'
		),
		'CG' => array(
			'wof:id' => 85632541,
			'wof:name' => 'Republic of Congo'
		),
		'VN' => array(
			'wof:id' => 85632763,
			'wof:name' => 'Vietnam'
		),
		'RO' => array(
			'wof:id' => 85633745,
			'wof:name' => 'Romania'
		),
		'MY' => array(
			'wof:id' => 85632739,
			'wof:name' => 'Malaysia'
		),
		'OM' => array(
			'wof:id' => 85632207,
			'wof:name' => 'Oman'
		),
		'CI' => array(
			'wof:id' => 85632449,
			'wof:name' => 'Ivory Coast'
		),
		'PH' => array(
			'wof:id' => 85632509,
			'wof:name' => 'Philippines'
		),
		'BF' => array(
			'wof:id' => 85632213,
			'wof:name' => 'Burkina Faso'
		),
		'KG' => array(
			'wof:id' => 85632761,
			'wof:name' => 'Kyrgyzstan'
		),
		'GA' => array(
			'wof:id' => 85632407,
			'wof:name' => 'Gabon'
		),
		'EC' => array(
			'wof:id' => 85632261,
			'wof:name' => 'Ecuador'
		),
		'GN' => array(
			'wof:id' => 85632691,
			'wof:name' => 'Guinea'
		),
		'XX' => array(
			'wof:id' => 1108955787,
			'wof:name' => 'Socialist Federal Republic of Yugoslavia'
		),
		'LA' => array(
			'wof:id' => 85632241,
			'wof:name' => 'Laos'
		),
		'UG' => array(
			'wof:id' => 85632625,
			'wof:name' => 'Uganda'
		),
		'GH' => array(
			'wof:id' => 85632189,
			'wof:name' => 'Ghana'
		),
		'IS' => array(
			'wof:id' => 85633249,
			'wof:name' => 'Iceland'
		),
		'SY' => array(
			'wof:id' => 85632413,
			'wof:name' => 'Syria'
		),
		'XX' => array(
			'wof:id' => 1108955785,
			'wof:name' => 'Socialist Federal Republic of Yugoslavia'
		),
		'UY' => array(
			'wof:id' => 85632511,
			'wof:name' => 'Uruguay'
		),
		'SN' => array(
			'wof:id' => 85632365,
			'wof:name' => 'Senegal'
		),
		'GY' => array(
			'wof:id' => 85632397,
			'wof:name' => 'Guyana'
		),
		'TN' => array(
			'wof:id' => 85632703,
			'wof:name' => 'Tunisia'
		),
		'KH' => array(
			'wof:id' => 85632359,
			'wof:name' => 'Cambodia'
		),
		'TJ' => array(
			'wof:id' => 85632513,
			'wof:name' => 'Tajikistan'
		),
		'GR' => array(
			'wof:id' => 85633171,
			'wof:name' => 'Greece'
		),
		'XS' => array(
			'wof:id' => 85632733,
			'wof:name' => 'Somaliland'
		),
		'NP' => array(
			'wof:id' => 85632465,
			'wof:name' => 'Nepal'
		),
		'KP' => array(
			'wof:id' => 85632639,
			'wof:name' => 'North Korea'
		),
		'BD' => array(
			'wof:id' => 85632475,
			'wof:name' => 'Bangladesh'
		),
		'BG' => array(
			'wof:id' => 85633001,
			'wof:name' => 'Bulgaria'
		),
		'SR' => array(
			'wof:id' => 85632443,
			'wof:name' => 'Suriname'
		),
		'XX' => array(
			'wof:id' => 1108955783,
			'wof:name' => 'Federal Republic of Yugoslavia'
		),
		'HU' => array(
			'wof:id' => 85633237,
			'wof:name' => 'Hungary'
		),
		'NI' => array(
			'wof:id' => 85632599,
			'wof:name' => 'Nicaragua'
		),
		'ER' => array(
			'wof:id' => 85632781,
			'wof:name' => 'Eritrea'
		),
		'AT' => array(
			'wof:id' => 85632785,
			'wof:name' => 'Austria'
		),
		'KR' => array(
			'wof:id' => 85632231,
			'wof:name' => 'South Korea'
		),
		'MW' => array(
			'wof:id' => 85632383,
			'wof:name' => 'Malawi'
		),
		'CZ' => array(
			'wof:id' => 85633105,
			'wof:name' => 'Czech Republic'
		),
		'CU' => array(
			'wof:id' => 85632675,
			'wof:name' => 'Cuba'
		),
		'PT' => array(
			'wof:id' => 85633735,
			'wof:name' => 'Portugal'
		),
		'LV' => array(
			'wof:id' => 85633279,
			'wof:name' => 'Latvia'
		),
		'BJ' => array(
			'wof:id' => 85632247,
			'wof:name' => 'Benin'
		),
		'HN' => array(
			'wof:id' => 85632323,
			'wof:name' => 'Honduras'
		),
		'IE' => array(
			'wof:id' => 85633241,
			'wof:name' => 'Ireland'
		),
		'GT' => array(
			'wof:id' => 85632385,
			'wof:name' => 'Guatemala'
		),
		'LT' => array(
			'wof:id' => 85633269,
			'wof:name' => 'Lithuania'
		),
		'AZ' => array(
			'wof:id' => 85632717,
			'wof:name' => 'Azerbaijan'
		),
		'RS' => array(
			'wof:id' => 85633755,
			'wof:name' => 'Serbia'
		),
		'JO' => array(
			'wof:id' => 85632425,
			'wof:name' => 'Jordan'
		),
		'EH' => array(
			'wof:id' => 85632217,
			'wof:name' => 'Western Sahara'
		),
		'LR' => array(
			'wof:id' => 85632249,
			'wof:name' => 'Liberia'
		),
		'GE' => array(
			'wof:id' => 85633163,
			'wof:name' => 'Georgia'
		),
		'EE' => array(
			'wof:id' => 85633135,
			'wof:name' => 'Estonia'
		),
		'FR' => array(
			'wof:id' => 85632233,
			'wof:name' => 'French Guiana'
		),
		'HR' => array(
			'wof:id' => 85633229,
			'wof:name' => 'Croatia'
		),
		'AE' => array(
			'wof:id' => 85632573,
			'wof:name' => 'United Arab Emirates'
		),
		'PA' => array(
			'wof:id' => 85632179,
			'wof:name' => 'Panama'
		),
		'DK' => array(
			'wof:id' => 85633121,
			'wof:name' => 'Denmark'
		),
		'SK' => array(
			'wof:id' => 85633769,
			'wof:name' => 'Slovakia'
		),
		'SL' => array(
			'wof:id' => 85632467,
			'wof:name' => 'Sierra Leone'
		),
		'BA' => array(
			'wof:id' => 85632609,
			'wof:name' => 'Bosnia and Herzegovina'
		),
		'NL' => array(
			'wof:id' => 85633337,
			'wof:name' => 'Netherlands'
		),
		'LK' => array(
			'wof:id' => 85632313,
			'wof:name' => 'Sri Lanka'
		),
		'CH' => array(
			'wof:id' => 85633051,
			'wof:name' => 'Switzerland'
		),
		'TG' => array(
			'wof:id' => 85632647,
			'wof:name' => 'Togo'
		),
		'CR' => array(
			'wof:id' => 85632487,
			'wof:name' => 'Costa Rica'
		),
		'DO' => array(
			'wof:id' => 85632713,
			'wof:name' => 'Dominican Republic'
		),
		'MD' => array(
			'wof:id' => 85633287,
			'wof:name' => 'Moldova'
		),
		'BE' => array(
			'wof:id' => 85632997,
			'wof:name' => 'Belgium'
		),
		'BT' => array(
			'wof:id' => 85632171,
			'wof:name' => 'Bhutan'
		),
		'TW' => array(
			'wof:id' => 85632403,
			'wof:name' => 'Taiwan'
		),
		'AM' => array(
			'wof:id' => 85632773,
			'wof:name' => 'Armenia'
		),
		'AL' => array(
			'wof:id' => 85632405,
			'wof:name' => 'Albania'
		),
		'LS' => array(
			'wof:id' => 85632173,
			'wof:name' => 'Lesotho'
		),
		'GW' => array(
			'wof:id' => 85632757,
			'wof:name' => 'Guinea Bissau'
		),
		'MK' => array(
			'wof:id' => 85632373,
			'wof:name' => 'Macedonia'
		),
		'SB' => array(
			'wof:id' => 85632591,
			'wof:name' => 'Solomon Islands'
		),
		'SI' => array(
			'wof:id' => 85633779,
			'wof:name' => 'Slovenia'
		),
		'HT' => array(
			'wof:id' => 85632433,
			'wof:name' => 'Haiti'
		),
		'GQ' => array(
			'wof:id' => 85632287,
			'wof:name' => 'Equatorial Guinea'
		),
		'BI' => array(
			'wof:id' => 85632285,
			'wof:name' => 'Burundi'
		),
		'RW' => array(
			'wof:id' => 85632303,
			'wof:name' => 'Rwanda'
		),
		'IL' => array(
			'wof:id' => 85632315,
			'wof:name' => 'Israel'
		),
		'BZ' => array(
			'wof:id' => 85632571,
			'wof:name' => 'Belize'
		),
		'DJ' => array(
			'wof:id' => 85632319,
			'wof:name' => 'Djibouti'
		),
		'SV' => array(
			'wof:id' => 85632545,
			'wof:name' => 'El Salvador'
		),
		'FJ' => array(
			'wof:id' => 85632755,
			'wof:name' => 'Fiji'
		),
		'KW' => array(
			'wof:id' => 85632401,
			'wof:name' => 'Kuwait'
		),
		'SZ' => array(
			'wof:id' => 85632635,
			'wof:name' => 'Swaziland'
		),
		'ME' => array(
			'wof:id' => 85632667,
			'wof:name' => 'Montenegro'
		),
		'TL' => array(
			'wof:id' => 85632583,
			'wof:name' => 'East Timor'
		),
		'XK' => array(
			'wof:id' => 85633259,
			'wof:name' => 'Kosovo'
		),
		'BS' => array(
			'wof:id' => 85632339,
			'wof:name' => 'The Bahamas'
		),
		'VU' => array(
			'wof:id' => 85632263,
			'wof:name' => 'Vanuatu'
		),
		'QA' => array(
			'wof:id' => 85632299,
			'wof:name' => 'Qatar'
		),
		'LB' => array(
			'wof:id' => 85632533,
			'wof:name' => 'Lebanon'
		),
		'JM' => array(
			'wof:id' => 85632215,
			'wof:name' => 'Jamaica'
		),
		'GM' => array(
			'wof:id' => 85632603,
			'wof:name' => 'Gambia'
		),
		'PS' => array(
			'wof:id' => 85633739,
			'wof:name' => 'Palestine'
		),
		'CY' => array(
			'wof:id' => 85632437,
			'wof:name' => 'Cyprus'
		),
		'BN' => array(
			'wof:id' => 85632749,
			'wof:name' => 'Brunei'
		),
		'TT' => array(
			'wof:id' => 85632271,
			'wof:name' => 'Trinidad and Tobago'
		),
		'CV' => array(
			'wof:id' => 85632721,
			'wof:name' => 'Cape Verde'
		),
		'LU' => array(
			'wof:id' => 85633275,
			'wof:name' => 'Luxembourg'
		),
		'FR' => array(
			'wof:id' => 85632351,
			'wof:name' => 'Reunion'
		),
		'WS' => array(
			'wof:id' => 85632681,
			'wof:name' => 'Samoa'
		),
		'MU' => array(
			'wof:id' => 85632357,
			'wof:name' => 'Mauritius'
		),
		'FR' => array(
			'wof:id' => 85632423,
			'wof:name' => 'Guadeloupe'
		),
		'KM' => array(
			'wof:id' => 85632259,
			'wof:name' => 'Comoros'
		),
		'FR' => array(
			'wof:id' => 85632531,
			'wof:name' => 'Martinique'
		),
		'HK' => array(
			'wof:id' => 85632483,
			'wof:name' => 'Hong Kong S.A.R.'
		),
		'KI' => array(
			'wof:id' => 85632709,
			'wof:name' => 'Kiribati'
		),
		'IM' => array(
			'wof:id' => 85632461,
			'wof:name' => 'Isle of Man'
		),
		'ST' => array(
			'wof:id' => 85632765,
			'wof:name' => 'Sao Tome and Principe'
		),
		'FM' => array(
			'wof:id' => 85632431,
			'wof:name' => 'Federated States of Micronesia'
		),
		'TO' => array(
			'wof:id' => 85632455,
			'wof:name' => 'Tonga'
		),
		'DM' => array(
			'wof:id' => 85632503,
			'wof:name' => 'Dominica'
		),
		'BH' => array(
			'wof:id' => 85632167,
			'wof:name' => 'Bahrain'
		),
		'LC' => array(
			'wof:id' => 85632369,
			'wof:name' => 'Saint Lucia'
		),
		'AD' => array(
			'wof:id' => 85632343,
			'wof:name' => 'Andorra'
		),
		'SG' => array(
			'wof:id' => 85632605,
			'wof:name' => 'Singapore'
		),
		'PW' => array(
			'wof:id' => 85632331,
			'wof:name' => 'Palau'
		),
		'SC' => array(
			'wof:id' => 85632661,
			'wof:name' => 'Seychelles'
		),
		'AG' => array(
			'wof:id' => 85632529,
			'wof:name' => 'Antigua and Barbuda'
		),
		'CW' => array(
			'wof:id' => 85632441,
			'wof:name' => 'Curacao'
		),
		'BB' => array(
			'wof:id' => 85632491,
			'wof:name' => 'Barbados'
		),
		'VC' => array(
			'wof:id' => 85632569,
			'wof:name' => 'Saint Vincent and the Grenadines'
		),
		'FR' => array(
			'wof:id' => 85632523,
			'wof:name' => 'Mayotte'
		),
		'MT' => array(
			'wof:id' => 85633331,
			'wof:name' => 'Malta'
		),
		'GD' => array(
			'wof:id' => 85632335,
			'wof:name' => 'Grenada'
		),
		'PM' => array(
			'wof:id' => 85632371,
			'wof:name' => 'Saint Pierre and Miquelon'
		),
		'AN' => array(
			'wof:id' => 85632727,
			'wof:name' => 'Netherlands'
		),
		'MV' => array(
			'wof:id' => 85632305,
			'wof:name' => 'Maldives'
		),
		'KN' => array(
			'wof:id' => 85632551,
			'wof:name' => 'Saint Kitts and Nevis'
		),
		'MH' => array(
			'wof:id' => 85632663,
			'wof:name' => 'Marshall Islands'
		),
		'LI' => array(
			'wof:id' => 85633267,
			'wof:name' => 'Liechtenstein'
		),
		'JE' => array(
			'wof:id' => 85632593,
			'wof:name' => 'Jersey'
		),
		'AW' => array(
			'wof:id' => 85632295,
			'wof:name' => 'Aruba'
		),
		'CC' => array(
			'wof:id' => 85632495,
			'wof:name' => 'Indian Ocean Territories'
		),
		'GG' => array(
			'wof:id' => 85632547,
			'wof:name' => 'Guernsey'
		),
		'SM' => array(
			'wof:id' => 85633763,
			'wof:name' => 'San Marino'
		),
		'TV' => array(
			'wof:id' => 85632607,
			'wof:name' => 'Tuvalu'
		),
		'SX' => array(
			'wof:id' => 85632185,
			'wof:name' => 'Sint Maarten'
		),
		'NR' => array(
			'wof:id' => 85632747,
			'wof:name' => 'Nauru'
		),
		'MO' => array(
			'wof:id' => 85632161,
			'wof:name' => 'Macao S.A.R'
		),
		'MC' => array(
			'wof:id' => 85633285,
			'wof:name' => 'Monaco'
		),
		'VA' => array(
			'wof:id' => 85632187,
			'wof:name' => 'Vatican'
		),
		'UN' => array(
			'wof:id' => 102312305,
			'wof:name' => 'United Nations'
		),
		'XN' => array(
			'wof:id' => 1,
			'wof:name' => 'Null Island'
		),
	);

	# the end