<?php

        # this file was cloned from https://github.com/whosonfirst/flamework-whosonfirst/

        ########################################################################

        # this file was also generated by robots on 2017-11-27T20:06:39.751649
        # https://github.com/whosonfirst/flamework-whosonfirst/blob/master/utils/mk-spec.py
        # https://github.com/whosonfirst/flamework-whosonfirst/blob/master/Makefile

        ########################################################################

        $GLOBALS['whosonfirst_brands_sizes']['__SPEC__'] = '{"1141959937": {"min": 6, "max": 10, "label": "extra-extra small", "id": 1141959937, "name": "XXS"}, "1158862561": {"min": 1, "max": 2, "label": "onesie", "id": 1158862561, "name": "O"}, "1141959923": {"min": 21, "max": 50, "label": "small", "id": 1141959923, "name": "S"}, "1141959925": {"min": 101, "max": 500, "label": "large", "id": 1141959925, "name": "L"}, "1141959927": {"min": 51, "max": 100, "label": "medium", "id": 1141959927, "name": "M"}, "1141959929": {"min": 501, "max": 5000, "label": "extra large", "id": 1141959929, "name": "XL"}, "1141959931": {"min": 11, "max": 20, "label": "extra small", "id": 1141959931, "name": "XS"}, "1141959935": {"min": 5001, "max": 10000, "label": "extra-extra large", "id": 1141959935, "name": "XXL"}}';

        ########################################################################
        # the end
